sudo: false

language: python

python:
    - 3.3
    - 3.4
    - 3.5

install:
    # Install Neovim via Gist
    # https://gist.github.com/lambdalisue/0f461f6a91743895394e63a9a1c65232
    - curl -sL git.io/v18DU | bash
    - make install

script:
    - PATH="$HOME/neovim/bin:$PATH" make test
    - make lint
